# Generated by Django 5.0.6 on 2024-06-17 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_food_category'),
        ('main', '0003_alter_category_context_name'),
    ]

    operations = [
    ]
